#!/bin/bash
if [ $# -lt 2 ]; then
	echo "Usage: $0 <essid> <password> <interface(wlan0)>"
	exit 1
fi
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

ESSID=$1
PASSWD=$2
IFACE=$3

if [ ${#PASSWD} -lt 8 ]; then
	echo "Password must be 8 or more characters"
	exit 1
fi

if [ "$IFACE" == "" ]; then
	IFACE="wlan0"
fi

echo "Setting $ESSID with password \"$2\"..."
wpa_passphrase $ESSID $PASSWD >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "Applying changes to $IFACE..."
ifconfig $IFACE down
ifconfig $IFACE up
dhcpcd $IFACE
